### ISSUE TITLE
Error en final 14/07/2015

### ISSUE THREAD

**Issue by leoxs22** [JuanQP/arquitectura-finales#1]
En una unidad de disco 10 cabezas lecto/grabadoras describen 18000 Círculos concéntricos en el soporte.
¿Cuántos cilindros se describen?

Creo que son 1.800, no 18.000.
Osea, tengo 1.800 cilindros * 10 cabezas = 18.000 pistas

**Comment by JuanQP** [comment]
¿Podrías por favor citar la página del libro o fuente en donde encontraste esa información? Así tu afirmación la podemos contrastar con algo sobre lo que podamos debatir (si no, tenemos que recurrir al *a mí me parece que...*, y es mucho más difícil 😛 )

**Comment by leoxs22** [comment]
Nah, no encontré eso exacto en algún lugar, pero por la definición creo que sería así:
https://tiposdecomputadora.wordpress.com/2011/05/23/estructura-logica-de-un-disco-duro-cilindros-cabezas-sectores-pistas-cluster%E2%80%A6/

Cilindro: Conjunto de varias pistas; son todas las circunferencias que están alineadas verticalmente (una de cada cara).

10 cabezas, 10 caras, osea, 10 círculos por cada cilindro.

**Comment by JuanQP** [comment]
Hace unos días aprobé la cursada de Sistemas Operativos, y volvimos a ver muchos de estos temas, y efectivamente estabas en lo cierto, ahí hice la corrección :laughing:
